saalfeldlab/n5

src/main/java/org/janelia/saalfeldlab/n5/N5.java

N5Test was failing on my machine (Ubuntu, $HOME stored on NFS) due to not being able to remove an N5 dataset. Further debugging showed that it could not delete a directory which should be empty but actually was not.
It turned out that a file channel was never closed after the file deletion, and an auto-generated file .nrsXXXXX was left in that directory. Closing the file channel fixes the issue.

Fix N5.remove() on NFS

---

src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java
src/main/java/org/janelia/saalfeldlab/n5/N5Reader.java
src/test/java/org/janelia/saalfeldlab/n5/N5Test.java

https://github.com/saalfeldlab/n5/blob/1.1.1/src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java#L245
The above code behaves incorrectly in the case there is a group with the same name but with no attributes. It throws an `IOException` (tries to load missing file _attributes.json_). But I would expect it to return `false` as in the case when the attributes are not consistent with the mandatory dataset attributes.
This PR introduces `hasAttributes()` method which tests whether a file _attributes.json_ exists. This method also allows to safely test for its existence before reading the attributes of a group (where this file is not guaranteed to be present).

Fix dataset existence check

---

src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java

The file stream in `N5FSReader.list()` was never closed which was causing a leak.
I implemented parallel remove operation for N5 containers, and at some point it threw `java.nio.file.FileSystemException: Too many open files`. Closing the stream fixes the issue.

Fix files stream leak in list()

---

src/main/java/org/janelia/saalfeldlab/n5/ByteArrayDataBlock.java
src/main/java/org/janelia/saalfeldlab/n5/DataBlock.java
src/main/java/org/janelia/saalfeldlab/n5/DataType.java
src/main/java/org/janelia/saalfeldlab/n5/DoubleArrayDataBlock.java
src/main/java/org/janelia/saalfeldlab/n5/FloatArrayDataBlock.java
src/main/java/org/janelia/saalfeldlab/n5/IntArrayDataBlock.java
src/main/java/org/janelia/saalfeldlab/n5/LongArrayDataBlock.java
src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java
src/main/java/org/janelia/saalfeldlab/n5/N5FSWriter.java
src/main/java/org/janelia/saalfeldlab/n5/ShortArrayDataBlock.java

changed first two bytes of N5FS file format to represent a mode, where 0
indicates the old 'mode' (for backwards compatibility), and 1 indicates
that there is another integer stored after the dimensions representing
the number of elements, necessary for future flexibility

Add flexibility to N5FS for numElements

---

src/main/java/org/janelia/saalfeldlab/n5/N5FSWriter.java
src/test/java/org/janelia/saalfeldlab/n5/N5Test.java

When the mode is 1 (determined automatically by the `N5FSWriter` depending on whether `numElements` equals `getNumElements(getSize())`), `numElements` should have been written after the dimensions and before the data, as [specified](https://github.com/saalfeldlab/n5#specifications), and as `N5FSReader` [expects](https://github.com/saalfeldlab/n5/blob/master/src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java#L236). Also adds a test case to make sure this functionality isn't broken by a future change.

Fix N5FSWriter not writing numElements in mode=1

---

src/main/java/org/janelia/saalfeldlab/n5/BlockReader.java
src/main/java/org/janelia/saalfeldlab/n5/BlockWriter.java
src/main/java/org/janelia/saalfeldlab/n5/DefaultBlockReader.java
src/main/java/org/janelia/saalfeldlab/n5/DefaultBlockWriter.java
src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java
src/main/java/org/janelia/saalfeldlab/n5/N5FSWriter.java
src/test/java/org/janelia/saalfeldlab/n5/AbstractN5Test.java

- Changed default block readers/writers to work with IO streams instead of NIO channels
- Moved block metadata handling to default block readers/writers
- Fixed the issue with incomplete buffer reading #12

Default block readers/writers

---

src/main/java/org/janelia/saalfeldlab/n5/AbstractGsonReader.java
src/main/java/org/janelia/saalfeldlab/n5/DefaultGsonReader.java
src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java
src/main/java/org/janelia/saalfeldlab/n5/N5FSWriter.java

Another small change that I would like to make:
- Moved `gson` object instantiation to `AbstractGsonReader` (formerly `DefaultGsonReader`)
This allows to omit setting up proper type adapters for the mandatory attributes in the implementations.

AbstractGsonReader

---

src/main/java/org/janelia/saalfeldlab/n5/AbstractN5FSReader.java
src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java
src/main/java/org/janelia/saalfeldlab/n5/N5FSWriter.java
src/main/java/org/janelia/saalfeldlab/n5/N5Reader.java
src/main/java/org/janelia/saalfeldlab/n5/N5VersionedReader.java
src/main/java/org/janelia/saalfeldlab/n5/N5VersionedWriter.java
src/main/java/org/janelia/saalfeldlab/n5/N5Writer.java
src/test/java/org/janelia/saalfeldlab/n5/AbstractN5Test.java
src/test/java/org/janelia/saalfeldlab/n5/AbstractN5VersionedTest.java
src/test/java/org/janelia/saalfeldlab/n5/N5FSTest.java

This PR allows to easily support versioning functionality in derived N5 implementations and to use the abstract test set for testing non-json based N5 implementations.
* Add new interfaces `N5VersionedReader` and `N5VersionedWriter`
* Remove `GsonAttributesParser` dependency in `AbstractN5Test`
* Add versioning test
* Fix `testExists()` by removing too restrictive assertion that depended on particular execution order
* Add test case to ensure that `n5.exists()` properly returns `false` when a group does not exist

Improve tests & versioning

---

src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java

On some file systems a file lock cannot be acquired when the directory is not writable (for example, SMB lock). Do not fail in this case and proceed without locking as a fallback.

Do not throw IOException when unable to acquire file lock

---

src/main/java/org/janelia/saalfeldlab/n5/N5FSWriter.java

Prevents the following issues when using N5Writer in a parallel environment where file locking does not work across machines (for example, NFS):
* possible JSON format exception when read by one machine while being written by another machine
* possible corruption of attributes.json file when written simultaneously by multiple machines

Fix unnecessary version overwriting when versions are equal

---

src/main/java/org/janelia/saalfeldlab/n5/GzipCompression.java

Due to being marked `transient`, the `parameters` field was set to `null` after deserialization which was causing `NullPointerException` when trying to write a data block.

Initialize GzipCompression parameters after deserialization

---

README.md

Two small doc inconsistencies I've run across reimplementing this in rust.
- The name of the version attribute key did not match what is used in `N5Reader`
- Block ndim was listed as a `uint32`, but is `uint16` in the example hex and read with `getShort` in `DefaultBlockReader`

Fix spec documentation

---

src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java
src/main/java/org/janelia/saalfeldlab/n5/N5FSWriter.java

A Windows user reported that N5 version check fails with
`java.nio.file.InvalidPathException: UNC path is missing sharename: /\attributes.json`.
Group/dataset paths starting with `/` or `\` are treated as UNC paths on Windows, and in some cases this makes `Paths.get()` fail. The fix is to remove the root slash from group/dataset paths so that they are properly treated as relative paths on both Unix and Windows platforms.

Fix InvalidPathException on Windows

---

pom.xml

When used with Spark 2.3.1, the old version was causing runtime errors.

Bump lz4 dependency to 1.4.0

---

src/main/java/org/janelia/saalfeldlab/n5/GzipCompression.java
src/test/java/org/janelia/saalfeldlab/n5/AbstractN5Test.java

Quick fix to support reading/writing gzip-compressed data with zlib headers which may be useful for compatibility with other libraries.
`apache-compress` gzip implementation does not seem to support zlib, so the standard java classes are used in this case.
The new parameter `useZlib` is optional and is not written to `attributes.json` by default (when it's `null`).

Support zlib headers in gzip compression

---

src/main/java/org/janelia/saalfeldlab/n5/AbstractGsonReader.java

This should be considered up for discussion. Do we want to be as restrictive as always disabling html escape? We could be less restrictive and adding a `boolean disableHtmlEscaping` parameter to the constructor that defaults to `true`. Then, callers could still enable html escaping if they wanted to.

Disable html escaping in AbstractGsonReader

---

src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java

I have a use-case where several threads sometimes may read the same N5 block, which leads to generating an `OverlappingFileLockException` and waiting for 100ms before retrying. That works fine, but if the thread is interrupted during that time, annoying error messages were printed. In this PR I removed excessive error printing and also added proper restoring of the interruption flag for the thread, so that the calling code can check it afterwards and handle it appropriately.

Improve thread interruption handling in LockedFileChannel

---

src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java

Useful for debugging, does not add any additional dependencies (unlike #48)
Closes #47 
cc @axtimwalde

Override N5FSReader.toString

---

pom.xml

`saalfedllab` -> `saalfeldlab`

Fix typo in scm connection

---

pom.xml
src/main/java/org/janelia/saalfeldlab/n5/CompressionAdapter.java
src/main/java/org/janelia/saalfeldlab/n5/GzipCompression.java
src/main/java/org/janelia/saalfeldlab/n5/ReflectionUtils.java

The problem with newer versions of Java was that the following exception was thrown at runtime:
`java.lang.NoSuchFieldException: modifiers at java.base/java.lang.Class.getDeclaredField(Class.java:2416)`
The modifiers field is hidden from reflection in Java 11+, but it turns out that it's not necessary anymore to reset the `final` modifier so just setting the field value through reflection works in Oracle JDK 13.

Add compatibility with Java 13

---

src/test/java/org/janelia/saalfeldlab/n5/AbstractN5Test.java

In my use-case I would like to remove temporary data after all tests are completed which is specific to the test environment. Normally it can be done in a method annotated with `@AfterClass`, but it requires the method to be static which doesn't go well with inheritance.
This PR adds a `cleanup()` method in `AbstractN5Test`. It's empty by default, and the actual test classes may optionally override it to do any additional cleanup if needed.

Improve initialization and cleanup in AbstractN5Test

---

src/main/java/org/janelia/saalfeldlab/n5/N5FSWriter.java

Closes #63
It seems that deleting files under the lock was the cause for `DirectoryNotEmptyException` on a network file system. Presumably the lock file sometimes is not cleared immediately after the actual file is deleted, so the directory cannot be removed because it still contains the temporary lock file. But, the directory contents show up as empty right after the exception is thrown, so it looks like a timing or synchronization issue on the network file system.
Deleting the files without locking solves it. It's probably a very unlikely use case anyway to keep reading/writing the N5 dataset files while deleting it, so I don't think that no locking will be a problem here.

Fix occasional DirectoryNotEmptyException when removing files on NFS

---

src/main/java/org/janelia/saalfeldlab/n5/N5FSWriter.java

This is another solution for #63 and improves upon #64 by keeping file locking when removing group/dataset. When `DirectoryNotEmptyException` is thrown because of the temporary lock file, it waits for 100ms and re-attempts to delete the directory.
I've tested it and it works well: if it fails for the first time, the re-attempt always succeeds.

Better fix for DirectoryNotEmptyException by re-attempting to delete

---

src/test/java/org/janelia/saalfeldlab/n5/AbstractN5Test.java
src/test/java/org/janelia/saalfeldlab/n5/N5FSTest.java

I started updating and testing `n5-aws-s3` and `n5-google-cloud` to support block deletion, and I thought that it would be helpful to make null-check a default implementation of the block existence test in `N5AbstractTest`. All implementations return `null` for a missing block except `n5-hdf5` which is a special case, so instead of repeating the default null-check in every implementation it could be only overridden in `n5-hdf5`.

Default null-check implementation of isBlockDeleted() in unit tests

---

README.md
pom.xml
src/main/java/org/janelia/saalfeldlab/n5/AbstractGsonReader.java
src/main/java/org/janelia/saalfeldlab/n5/DataType.java
src/main/java/org/janelia/saalfeldlab/n5/DefaultBlockReader.java
src/main/java/org/janelia/saalfeldlab/n5/DefaultBlockWriter.java
src/main/java/org/janelia/saalfeldlab/n5/GsonAttributesParser.java
src/main/java/org/janelia/saalfeldlab/n5/N5FSReader.java
src/main/java/org/janelia/saalfeldlab/n5/N5FSWriter.java
src/main/java/org/janelia/saalfeldlab/n5/N5Reader.java
src/main/java/org/janelia/saalfeldlab/n5/N5Writer.java
src/test/java/org/janelia/saalfeldlab/n5/AbstractN5Test.java
src/test/java/org/janelia/saalfeldlab/n5/N5Benchmark.java

* introduces DataType.OBJECT that maps to bytes
* introduces block mode 2 because serialized objects do not have a blocksize or
number of dimensions

add methods to read and write serializable objects as datablocks

---

src/main/java/org/janelia/saalfeldlab/n5/N5Reader.java
src/test/java/org/janelia/saalfeldlab/n5/AbstractN5Test.java

This PR adds a default method `deepList` to `N5Reader` which recursively returns all datasets that are children of the argument path.
It also provides a `deepListParallel` that performs the listing / dataset detection in parallel using an `ExecutorService`
I'd like to check that high-latency (cloud) readers behave correctly - I've experienced issues in the past.

add default deepList to N5Reader

---

README.md
pom.xml

This updates the jhdf5 library to version 19.04.0 per scijava/pom-scijava#181

Bump scijava-pom to 31.1.0, jhdf5 to 19.04

---

src/main/java/org/janelia/saalfeldlab/n5/GzipCompression.java

Direct concatenation of gzip streams is a valid gzip stream [(see the gzip spec)](https://datatracker.ietf.org/doc/html/rfc1952#section-2.3).
Such streams currently fail with an `EOFException`, This PR enables such streams to be correctly read. 
<details>
<summary>the exception</summary>
```
Caused by: java.io.EOFException
at java.io.DataInputStream.readFully(DataInputStream.java:197)
at java.io.DataInputStream.readFully(DataInputStream.java:169)
at org.janelia.saalfeldlab.n5.DefaultBlockReader.read(DefaultBlockReader.java:51)
at org.janelia.saalfeldlab.n5.zarr.N5ZarrReader.readBlock(N5ZarrReader.java:350)
at org.janelia.saalfeldlab.n5.zarr.N5ZarrReader.readBlock(N5ZarrReader.java:470)
at org.janelia.saalfeldlab.n5.imglib2.N5CacheLoader.get(N5CacheLoader.java:117)
at …
```

fix: read multi-member gzip streams

---

src/main/java/org/janelia/saalfeldlab/n5/CachedGsonKeyValueN5Writer.java
src/main/java/org/janelia/saalfeldlab/n5/GsonKeyValueN5Reader.java
src/main/java/org/janelia/saalfeldlab/n5/GsonKeyValueN5Writer.java
src/main/java/org/janelia/saalfeldlab/n5/N5Exception.java
src/main/java/org/janelia/saalfeldlab/n5/N5Reader.java
src/main/java/org/janelia/saalfeldlab/n5/N5Writer.java

AccessDeniedExceptions are UncheckedIOExceptions, and were not being wrapped by N5IOExceptions. This causes unexpected errors, such as deepList failing when unable to read nested n5 groups.

fix: wrap unchecked IOExceptions as well (such as AccessDenied)

---

src/main/java/org/janelia/saalfeldlab/n5/StringDataBlock.java

see https://github.com/saalfeldlab/n5-blosc/issues/7
This error was caused because the buffer not being backed by an accessible byte array.  The fix is to check if that is the case, and decode the buffer if not.

fix: UnsupportedOperationException for blosc and strings

---

pom.xml

And in particular, unpin the maven-enforcer-plugin, so that it can
roll forward without problems when the next pom-scijava release lands.

Unpin the enforcer plugin

---

src/main/java/org/janelia/saalfeldlab/n5/CompressionAdapter.java

Its pretty common for n5 to output (benign) errors when making a reader or writer if it can't find libblosc, for example.
This PR makes the error shorter 
<details>
<summary>from this</summary>
```
Compression 'org.janelia.saalfeldlab.n5.blosc.BloscCompression' could not be registered because:
java.lang.UnsatisfiedLinkError: Unable to load library 'blosc':
libblosc.so: cannot open shared object file: No such file or directory
libblosc.so: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libblosc.so) not found in resource path ([file:/home/john/dev/n5/n5-universe/target/test-classes/, file:/home/john/dev/n5/n5-universe/target/classes/, file:/home/john/.m2/repository/org/janelia/saalfeldlab/n5/3.2.0/n5-3.2.0.jar, …
```

Less verbose message when compressor loading fails

---

README.md

If the current version is 4.0.0, then the following part of the specification is incorrect.
> The version of this specification is 1.0.0 and is stored in the "n5" attribute of the root group "/".

Fix item 3 of the specification, update verison to 4.0.0

---

src/main/java/org/janelia/saalfeldlab/n5/N5Reader.java

It seems that on some systems (e.g. github actions) the order of the deepListHelper results is not gauranteed such that the first entry is always self.
When it is not, we throw away a needed result, and later get an error as we try to process a result which *is* self, and is an empty string. This causes the substring method to throw an error, though generally it is swallowed later, and rarely seen (another problem)

fix: assumption that the first deepListHelper result is always self

---

src/main/java/org/janelia/saalfeldlab/n5/CachedGsonKeyValueN5Reader.java
src/main/java/org/janelia/saalfeldlab/n5/HttpKeyValueAccess.java
src/main/java/org/janelia/saalfeldlab/n5/cache/N5JsonCache.java
src/main/java/org/janelia/saalfeldlab/n5/http/ApacheListResponseParser.java
src/main/java/org/janelia/saalfeldlab/n5/http/CandidateListResponseParser.java
src/main/java/org/janelia/saalfeldlab/n5/http/ListResponseParser.java
src/main/java/org/janelia/saalfeldlab/n5/http/MicrosoftListResponseParser.java
src/main/java/org/janelia/saalfeldlab/n5/http/PatternListResponseParser.java
src/main/java/org/janelia/saalfeldlab/n5/http/PythonListResponseParser.java
src/test/java/org/janelia/saalfeldlab/n5/N5CachedFSTest.java

Adds an interface `ListResponseParser` and two implementations:
* Python's SimpleHTTP
* Microsoft's IIS
Also updates HttpKeyValue access so that, on the first list call, a collection of known implementations are used,
and the first successful one is stored.
@cmhulbert

More extensible list response parsers

---

src/main/java/org/janelia/saalfeldlab/n5/Bzip2Compression.java
src/main/java/org/janelia/saalfeldlab/n5/CachedGsonKeyValueN5Writer.java
src/main/java/org/janelia/saalfeldlab/n5/Compression.java
src/main/java/org/janelia/saalfeldlab/n5/DefaultBlockReader.java
src/main/java/org/janelia/saalfeldlab/n5/DefaultBlockWriter.java
src/main/java/org/janelia/saalfeldlab/n5/FileSystemKeyValueAccess.java
src/main/java/org/janelia/saalfeldlab/n5/GsonKeyValueN5Reader.java
src/main/java/org/janelia/saalfeldlab/n5/GsonKeyValueN5Writer.java
src/main/java/org/janelia/saalfeldlab/n5/GsonUtils.java
src/main/java/org/janelia/saalfeldlab/n5/GzipCompression.java
src/main/java/org/janelia/saalfeldlab/n5/HttpKeyValueAccess.java
src/main/java/org/janelia/saalfeldlab/n5/KeyValueAccess.java
src/main/java/org/janelia/saalfeldlab/n5/LockedChannel.java
src/main/java/org/janelia/saalfeldlab/n5/Lz4Compression.java
src/main/java/org/janelia/saalfeldlab/n5/N5Exception.java
src/main/java/org/janelia/saalfeldlab/n5/XzCompression.java
src/main/java/org/janelia/saalfeldlab/n5/codec/DataBlockCodec.java
src/main/java/org/janelia/saalfeldlab/n5/codec/DataCodec.java
src/main/java/org/janelia/saalfeldlab/n5/codec/N5Codecs.java
src/main/java/org/janelia/saalfeldlab/n5/readdata/AbstractInputStreamReadData.java
src/main/java/org/janelia/saalfeldlab/n5/readdata/ByteArraySplittableReadData.java
src/main/java/org/janelia/saalfeldlab/n5/readdata/KeyValueAccessReadData.java
src/main/java/org/janelia/saalfeldlab/n5/readdata/LazyReadData.java
src/main/java/org/janelia/saalfeldlab/n5/readdata/ReadData.java
src/test/java/org/janelia/saalfeldlab/n5/N5Benchmark.java
src/test/java/org/janelia/saalfeldlab/n5/N5FSTest.java

when working with data backed by ReadData, it's not possible to know where the underlying data is coming from. We expect to deal with N5IOExceptions rather than IOException, especially when the ReadData is wrapping a KeyValueAccess read/write. This has the added benefit of letting the ReadData provider wrap the specific IOException with an appropriate N5 specific N5IOException, such as N5NoSuchKeyException.

Migrate IOExceptions to N5IOExceptions for ReadData and related logic

---

src/test/java/org/janelia/saalfeldlab/n5/http/RunnerWithHttpServer.java

With 72e9a7674b96ce916a48de00fa9e479e36888c84, a dependency on `python` is introduced. But on newer macOS versions, the system binary is `/usr/bin/python3`; there is no `python` binary nor symlink. So related tests here error out:
```
[ERROR] org.janelia.saalfeldlab.n5.http.N5HttpTest.null
[ERROR]   Run 1: N5HttpTest » IO Cannot run program "python" (in directory "/var/folders/58/xzyl05g94wb69j0vtbqdq92h0000gn/T/n5-http-test-server-3861032598968023987"): error=2, No such file or directory
[ERROR]   Run 2: N5HttpTest » NullPointer
[INFO]
[ERROR] org.janelia.saalfeldlab.n5.kva.HttpKeyValueAccessTest.null
[ERROR]   Run 1: HttpKeyValueAccessTest » IO Cannot run program "python" (in directory "/var/folders/58/xzyl05g94wb69j0vtbqdq92h0000gn/T/n5-http-test-server-3736070965945471518"): error=2, …
```

Use python3 rather than python on macOS
